name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: 'deploy'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Sleep for 1 minute
        run: sleep 60

      - name: Print successful status
        run: |
          echo "Deployment successful for commit ${{ github.sha }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
