name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 1 minute
        run: sleep 60

      - name: Print successful status
        run: echo "Deployment successful for PR ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.html_url }}"
